const gallery = [
  {
    src: "./src/assets/g2.jpg",
    alt: "Great Barrier Reef, Australia",
    days: "9-day trip",
    title: "Great Barrier Reef",
    country: "Australia",
    desc: "Dive into the vibrant underwater world of the Great Barrier \n Reef, a UNESCO World Heritage Site teeming with marine life.",
    price: "€2,500",
  },
  {
    src: "https://npf-prod.imgix.net/uploads/shutterstock_97706066_1.jpg?auto=compress%2Cformat&crop=focalpoint&fit=crop&fp-x=0.5&fp-y=0.5&h=900&q=80&w=1600",
    alt: "Gallery image",
    days: "7-day trip",
    title: "Grand Canyon",
    country: "United States",
    desc: "Stand in awe at the colossal beauty of the Grand Canyon, \n  carved by the forces of nature over millions of years.",
    price: "€1,200",
  },
  {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Machu_Picchu%2C_Peru.jpg/1200px-Machu_Picchu%2C_Peru.jpg",
    alt: "Gallery image",
    days: "10-day trip",
    title: "Machu Picchu",
    country: "Peru",
    desc: "Uncover the mystique of the ancient Inca ruins perched high \n in the Andes Mountains at Machu Picchu.",
    price: "€2,200",
  },
  {
    src: "https://media.cntraveler.com/photos/63f4f4fc0630e21ed8088321/4:3/w_5352,h_4014,c_limit/GettyImages-1145042281.jpeg",
    alt: "Gallery image",
    days: "11-day trip",
    title: "Bali",
    country: "Indonesia",
    desc: "Find tranquility on the idyllic island of Bali, with its \n lush landscapes, serene temples, and warm hospitality.",
    price: "€3,200",
  },
  {
    src: "https://a.cdn-hotels.com/gdcs/production143/d357/42fb6908-dcd5-4edb-9f8c-76208494af80.jpg",
    alt: "Gallery image",
    days: "5-day trip",
    title: "Rio de Janeiro",
    country: "Brazil",
    desc: "Experience the rhythm and energy of Rio de Janeiro, home to \n vibrant Carnival celebrations, iconic landmarks, and \n stunning beaches.",
    price: "€1,600",
  },
  {
    src: "https://travel.usnews.com/dims4/USNEWS/5707860/2147483647/resize/600x400%5E%3E/crop/600x400/quality/85/?url=https%3A%2F%2Ftravel.usnews.com%2Fimages%2Fniagara_falls_getty_main_MPPJRs4.jpg",
    alt: "Gallery image",
    days: "13-day trip",
    title: "Niagara Falls",
    country: "Canada",
    desc: "Immerse yourself in the breathtaking cascades and embark on \n unforgettable adventures in this natural wonder.",
    price: "€3,000",
  },
];

export default gallery;
